services:
  mongo:
    image: mongo:8.0
    container_name: picnia-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: picnia-database-test
    networks:
      - mongo

  picnia-nest-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: picnia-nest-server
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - mongo

networks:
  mongo:
    driver: bridge
